// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ChmodRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChmodRemote'](arg1, arg2, arg3);
}

export function CommandHistory(arg1) {
  return window['go']['main']['App']['CommandHistory'](arg1);
}

export function CompressRemote(arg1, arg2) {
  return window['go']['main']['App']['CompressRemote'](arg1, arg2);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function CopyProfileCredentials(arg1) {
  return window['go']['main']['App']['CopyProfileCredentials'](arg1);
}

export function CopyProfileSecret(arg1) {
  return window['go']['main']['App']['CopyProfileSecret'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRemote'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteRemote(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemote'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function ExtractRemote(arg1, arg2) {
  return window['go']['main']['App']['ExtractRemote'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function ImportLegacyDatabase() {
  return window['go']['main']['App']['ImportLegacyDatabase']();
}

export function ImportSSHConfig() {
  return window['go']['main']['App']['ImportSSHConfig']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListLocalDirectory(arg1) {
  return window['go']['main']['App']['ListLocalDirectory'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListRemote(arg1, arg2) {
  return window['go']['main']['App']['ListRemote'](arg1, arg2);
}

export function PickDownloadDirectory() {
  return window['go']['main']['App']['PickDownloadDirectory']();
}

export function PickPrivateKey() {
  return window['go']['main']['App']['PickPrivateKey']();
}

export function PickUploadSources() {
  return window['go']['main']['App']['PickUploadSources']();
}

export function RecordCommand(arg1, arg2) {
  return window['go']['main']['App']['RecordCommand'](arg1, arg2);
}

export function RenameRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemote'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2);
}

export function RevealProfileSecret(arg1) {
  return window['go']['main']['App']['RevealProfileSecret'](arg1);
}

export function SaveProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2, arg3);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function TrustHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrustHost'](arg1, arg2, arg3);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
