// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {localfiles} from '../models';
import {main} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function ChmodRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CommandHistory(arg1:number):Promise<Array<string>>;

export function CompressRemote(arg1:string,arg2:string):Promise<string>;

export function Connect(arg1:number,arg2:string,arg3:number,arg4:number):Promise<model.Connection>;

export function CopyProfileCredentials(arg1:number):Promise<void>;

export function CopyProfileSecret(arg1:number):Promise<void>;

export function CreateGroup(arg1:string):Promise<void>;

export function CreateRemote(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteRemote(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExtractRemote(arg1:string,arg2:string):Promise<string>;

export function GetAppInfo():Promise<model.AppInfo>;

export function ImportLegacyDatabase():Promise<number>;

export function ImportSSHConfig():Promise<Array<model.Profile>>;

export function ListGroups():Promise<Array<string>>;

export function ListLocalDirectory(arg1:string):Promise<localfiles.Directory>;

export function ListProfiles():Promise<Array<model.Profile>>;

export function ListRemote(arg1:string,arg2:string):Promise<model.Directory>;

export function PickDownloadDirectory():Promise<string>;

export function PickPrivateKey():Promise<string>;

export function PickUploadSources():Promise<main.UploadSelection>;

export function RecordCommand(arg1:number,arg2:string):Promise<void>;

export function RenameRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function RevealProfileSecret(arg1:number):Promise<string>;

export function SaveProfile(arg1:model.Profile,arg2:string,arg3:boolean):Promise<model.Profile>;

export function StartTerminal(arg1:string):Promise<void>;

export function TestConnection(arg1:model.Profile,arg2:string,arg3:boolean):Promise<void>;

export function TrustHost(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Upload(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
